### ISSUE TITLE
Duplicated styles

### ISSUE THREAD

**Issue by zachfedor** [Chedler1/more-css-practice#7]
https://github.com/Chedler1/more-css-practice/blob/a67f48f82b1c94cbb59bd6f415a6a9b75ae84e3b/airbnb/styles.css#L43-L58

Save yourself some trouble and learn how to select multiple elements at once and apple the same styles at once. It's easier to write, easier to read, easier to think about, and easier to maintain in the future. You could've had something as simple as:
```css
input {
  color: grey;
  font-size: 20px;
  /* etc. */
}
```
applied to every single input element that way you didn't have to do that for each one individually.
